name: "Bug"
description: "Something isn't working"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
