name: "Question"
description: "Ask a question that should be tracked"
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: q
    attributes:
      label: Question
    validations:
      required: true
  - type: input
    id: workstream
    attributes:
      label: Workstream (ws1 / ws2 / cross-cutting)
